language: node_js
node_js:
  - 11.9.0
before_script: 
  - cd ./front-end
  - npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: 9f0108a3-c86e-481e-a014-8e24c4fd34a5
  app: escar
  on:
repo: hiranthaR/escar